const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim Shirt",
      slug: "nike-slim-shirt",
      category: "Shirts",
      image: "/images/nike-p1.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      _id: "2",
      name: "Fit Pants",
      slug: "fit-shirt",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 190,
      brand: "Raymond",
      rating: 4.0,
      numReviews: 10,
      countInStock: 7,
      description: "High quality product",
    },
    {
      _id: "3",
      name: "Beautiful Shirt",
      slug: "beautiful-shirt",
      category: "Shirts",
      image: "/images/slim-p3.jpg",
      price: 100,
      brand: "Raymond",
      rating: 4.8,
      numReviews: 17,
      countInStock: 50,
      description: "A popular shirt",
    },
    {
      _id: "4",
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/golf-p4.jpg",
      price: 150,
      brand: "Nike",
      rating: 4.5,
      numReviews: 21,
      countInStock: 13,
      description: "A High quality pants",
    },
    {
      _id: "5",
      name: " Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/shirt5.jpg",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      _id: "6",
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants6.jpg",
      price: 70,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      countInStock: 2,
      description: "A popular pants",
    },
  ],
};
export default data;
